#!/bin/sh

echo "Compiling Riceupdate:"
g++ -g riceupdate.cpp -o riceupdate
echo ""

echo "Installing Pacman Dependencies:"
sudo pacman -S feh sed npm
echo ""

echo "Installing Ricemood (fhadiel):"
sudo npm install -g ricemood
echo "NOTE: IF YOU USE THE INCLUDED DOT FILES, COMMENT OUT THE SECTIONS OF THE CONFIG YOU DON'T NEED!"
echo ""

echo "Installed! Riceupdate Presets:"
echo ""

./riceupdate

echo ""

feh --bg-center placeholder.jpg

cp .config/ricemood ~/.config

echo "If you want to match my personal setup, you'll want to run 'install_optional'"

./riceupdate lavender