#!/bin/sh

echo "Compiling Riceupdate:"
g++ -g riceupdate.cpp -o riceupdate
echo ""

echo "Installing Pacman Dependencies:"
sudo pacman -S feh sed npm
echo ""

echo "Installing Ricemood (fhadiel):"
sudo npm install -g ricemood
echo ""


echo "Installed! Riceupdate Presets:"
echo ""

./riceupdate