#!/bin/sh

yay -S rofi sddm dunst polybar alacritty

git clone https://www.github.com/adi1090x/rofi

cd rofi

./setup.sh

git clone 

touch ${HOME}/.config/alacritty/alacritty.yml
touch ${HOME}/.config/polybar/config.ini
touch ${HOME}/.config/rofi/launchers/colorful/launcher.sh
touch ${HOME}/.config/rofi/launchers/colorful/launcherFull.sh
touch ${HOME}/.config/i3/config
touch ${HOME}/.config/rofi/powermenu/styles/bluish.rasi
touch ${HOME}/.config/dunst/dunstrc

riceupdate lavender
# touch /usr/share/sddm/themes/sddm-sugar-dark/theme.conf