#!/bin/sh

yay -S rofi sddm dunst polybar alacritty

git clone https://github.com/SapuSeven/rofi-presets

cd rofi

./setup.sh
mkdir ~/.config/alacritty
:> ${HOME}/.config/alacritty/alacritty.yml
mkdir ~/.config/polybar
:> ${HOME}/.config/polybar/config.ini
:> ${HOME}/.config/rofi/launchers/colorful/launcher.sh
:> ${HOME}/.config/rofi/launchers/colorful/launcherFull.sh
mkdir ~/.config/i3
:> ${HOME}/.config/i3/config
mkdir ~/.config/rofi
:> ${HOME}/.config/rofi/powermenu/styles/bluish.rasi
mkdir ~/.config/dunst
:> ${HOME}/.config/dunst/dunstrc

riceupdate lavender
# :> /usr/share/sddm/themes/sddm-sugar-dark/theme.conf