#!/bin/sh

yay -S rofi sddm dunst polybar alacritty

git clone https://www.github.com/adi1090x/rofi

cd rofi

./setup.sh

git clone 

:> ${HOME}/.config/alacritty/alacritty.yml
:> ${HOME}/.config/polybar/config.ini
:> ${HOME}/.config/rofi/launchers/colorful/launcher.sh
:> ${HOME}/.config/rofi/launchers/colorful/launcherFull.sh
:> ${HOME}/.config/i3/config
:> ${HOME}/.config/rofi/powermenu/styles/bluish.rasi
:> ${HOME}/.config/dunst/dunstrc

riceupdate lavender
# :> /usr/share/sddm/themes/sddm-sugar-dark/theme.conf